### ISSUE TITLE
Vince read through

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#11]
Could you read through this, make sure its clear etc. @drvinceknight 
I will be adding more on the lit review at some point when I find more papers

**Comment by drvinceknight** [comment]
On my phone, can you assign to me (you might already have).

**Comment by geraintpalmer** [comment]
I can't as you're not a collaborator sorry

**Comment by drvinceknight** [comment]
Ah right. Cool, have added to my other to-do list. Will take care of asap.

**Comment by geraintpalmer** [comment]
From your comments: you added 'absorbing' to the theorem, which isn't correct, so sticking to:

A deadlocked state arises at time $t$ if and only if there exists a weakly connected component of $D(t)$ that doesn't contain a sink vertex.

However, I think the following is true for absorbing deadlocks:

An absorbing deadlocked state arises at time $t$ if and only if $D(t)$ doesn't contain a sink vertex.
