### ISSUE TITLE
Graphs - Times to Deadlock

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#14]
For the 2 node network, simulating for 1000 iterations:
Base parameters:
L1 = 4.0
L2 = 5.0
mu1 = 10.0
mu2 = 8.0
r12 = 0.25
r21 = 0.15
n1 = 3
n2 = 2
- [x] L1, 2.5-14 in steps of 0.5
- [x] L2, 2.5-14 in steps of 0.5
- [x] mu1, 2.5-14 in steps of 0.5
- [x] mu2, 2.5-14 in steps of 0.5
- [x] r12, 0.1-1.0 in steps of 0.05
- [x] r21, 0.1-1.0 in steps of 0.05
- [x] n1, 0-6 in steps of 1
- [x] n2, 0-6 in steps of 1

**Comment by geraintpalmer** [comment]
Varying L1
![plot_vary_l1](https://cloud.githubusercontent.com/assets/9679702/7390060/f1ab3c9a-ee6b-11e4-8dc6-08521424060c.png)

**Comment by geraintpalmer** [comment]
Varying r12
![plot_vary_r12](https://cloud.githubusercontent.com/assets/9679702/7395512/3fbccb44-ee92-11e4-8474-a61231dd1305.png)

**Comment by drvinceknight** [comment]
Looking glorious.

MOAR!

![moar-cat](https://cloud.githubusercontent.com/assets/2131546/7396140/a153fdba-ee96-11e4-93fb-d50f4d58f71c.jpg)

**Comment by geraintpalmer** [comment]
Varying mu1
![plot_vary_mu1](https://cloud.githubusercontent.com/assets/9679702/7412060/bc9846da-ef36-11e4-9dba-bc8157704f25.png)

**Comment by drvinceknight** [comment]
Not as pretty... Run for longer still? How long are these going for?

**Comment by geraintpalmer** [comment]
1000 iterations.

**Comment by drvinceknight** [comment]
Would it cost much time to multiply that by 10?

**Comment by geraintpalmer** [comment]
That one with 1000 itrs had been running since 9:30, just finished.

**Comment by drvinceknight** [comment]
Ok, get a bunch on TWD running for much longer (just because we can). Not really necessary but the plots will be nicer to look at.

**Comment by geraintpalmer** [comment]
Varying n1
![plot_vary_n1](https://cloud.githubusercontent.com/assets/9679702/7417194/4d9dbb86-ef5c-11e4-9f76-4ea4862c9af4.png)

**Comment by drvinceknight** [comment]
Longer runs.

**Comment by geraintpalmer** [comment]
Varying L2
![plot_vary_l2](https://cloud.githubusercontent.com/assets/9679702/7420707/970277b6-ef76-11e4-9f57-fe170c8e0fd0.png)

**Comment by drvinceknight** [comment]
More iterations.

**Comment by geraintpalmer** [comment]
Now for the 2 node network, simulating for 10000 iterations:
Base parameters:
L1 = 4.0
L2 = 5.0
mu1 = 10.0
mu2 = 8.0
r12 = 0.25
r21 = 0.15
n1 = 3
n2 = 2
- [x] L1, 2.5-14 in steps of 0.5
- [x] L2, 2.5-14 in steps of 0.5
- [ ] mu1, 2.5-14 in steps of 0.5
- [ ] mu2, 2.5-14 in steps of 0.5
- [x] r12, 0.1-1.0 in steps of 0.05
- [ ] r21, 0.1-1.0 in steps of 0.05
- [x] n1, 0-6 in steps of 1
- [x] n2, 0-6 in steps of 1

**Comment by geraintpalmer** [comment]
varying L1 10000 itrs
![plot_vary_l1](https://cloud.githubusercontent.com/assets/9679702/7498531/670e3be2-f419-11e4-9186-5ef65d139c3b.png)

**Comment by geraintpalmer** [comment]
varying n1, 10000 itrs
![plot_vary_n1](https://cloud.githubusercontent.com/assets/9679702/7498535/7373247e-f419-11e4-9003-6e9ca64e88ca.png)

**Comment by drvinceknight** [comment]
Are these looking any better or are they the same as for 1000 iterations?
Looks similar to me...

**Comment by geraintpalmer** [comment]
Ie they look very similar to me

**Comment by drvinceknight** [comment]
Cool.

**Comment by geraintpalmer** [comment]
Varying L2
![plot_vary_l2](https://cloud.githubusercontent.com/assets/9679702/7517079/cb2c209c-f4ca-11e4-94a9-699f0d15ad57.png)

**Comment by geraintpalmer** [comment]
Varying n2
![plot_vary_n2](https://cloud.githubusercontent.com/assets/9679702/7517089/d7be77b0-f4ca-11e4-934b-c5ee660224b1.png)

**Comment by geraintpalmer** [comment]
Varying r12
![plot_vary_r12](https://cloud.githubusercontent.com/assets/9679702/7517099/e636c13a-f4ca-11e4-8b0a-e63e67a4c2c9.png)

**Comment by drvinceknight** [comment]
Is the calculation of the mean of the simulation taking account of the
removed outliers? If not perhaps throw it back in (this is a pie in the sky
suggestion).

**Comment by geraintpalmer** [comment]
No, removing outliers only removes them graphically. The red square for mean takes them into account.

**Comment by drvinceknight** [comment]
I thought so... We'll take another look at the MC.

**Comment by geraintpalmer** [comment]
varying r21
![plot_vary_r21](https://cloud.githubusercontent.com/assets/9679702/7534210/3d90bc88-f570-11e4-8f1a-e8e8a8f76a7a.png)
