### ISSUE TITLE
Try out violin plots for the time to deadlock

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#15]
These show the distribution slightly better than boxplots...

http://matplotlib.org/examples/statistics/violinplot_demo.html

**Comment by geraintpalmer** [comment]
![plotviol_vary_l1](https://cloud.githubusercontent.com/assets/9679702/8128888/769c5fc2-10fb-11e5-8e69-cf05c3931d94.png)
I can't see any options to get rid of outliers on violin plots, but I like how they show the distribution

**Comment by paulharper72** [comment]
Very nice Geraint  (although sitar plot would be more apt than violin!)

**Comment by drvinceknight** [comment]
What does that look like with less granularity? So L1 going up by 1 and not
1/2.

**Comment by geraintpalmer** [comment]
![plotviol_vary_l1_new](https://cloud.githubusercontent.com/assets/9679702/8159170/fb26394a-135b-11e5-9d76-264de20f5004.png)

**Comment by geraintpalmer** [comment]
![plotviol_vary_mu1](https://cloud.githubusercontent.com/assets/9679702/8159199/3972a10c-135c-11e5-8618-f1626df6e2de.png)

**Comment by drvinceknight** [comment]
These look real nice. Will be good to see the output of the statistical
test.

**Comment by geraintpalmer** [comment]
![plotviol_vary_r12](https://cloud.githubusercontent.com/assets/9679702/8159309/5451559e-135d-11e5-9151-eb9b93e0335a.png)
![plotviol_vary_n1](https://cloud.githubusercontent.com/assets/9679702/8159311/5a848940-135d-11e5-9cb0-fdd8db15cef3.png)
