### ISSUE TITLE
Further investigate validation of results

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#16]
- [x] Simulate MC
- [x] Find median analytically
- [x] Run simulation for **much** longer
- [x] Plot difference for given parameter set and increasing the number of runs

**Comment by geraintpalmer** [comment]
![plotviol_vary_r12](https://cloud.githubusercontent.com/assets/9679702/8328553/8521d672-1a69-11e5-8a47-4cab3b845460.png)
Not fantastic, still a bit out?

**Comment by geraintpalmer** [comment]
Not sure if increasing number of runs is going to improve results: plot mean against number of iterations (for 10000 iterations)
![movingmean0 85r12](https://cloud.githubusercontent.com/assets/9679702/8330018/3d7709d4-1a76-11e5-96e7-3bad307e3347.png)
![movingmean0 7r12](https://cloud.githubusercontent.com/assets/9679702/8330017/3d750a58-1a76-11e5-9a71-709f8dcb34c1.png)
![movingmean0 05r12](https://cloud.githubusercontent.com/assets/9679702/8330020/3d7bcf46-1a76-11e5-8e3e-b1cb9e2da64f.png)
![movingmean0 1r12](https://cloud.githubusercontent.com/assets/9679702/8330019/3d799906-1a76-11e5-94c0-c57bdde4541d.png)

**Comment by drvinceknight** [comment]
Add the expected value to this plots.

**Comment by geraintpalmer** [comment]
Makes it look even worse...
![movingmean0 85r12](https://cloud.githubusercontent.com/assets/9679702/8330474/80c94a46-1a79-11e5-9fbb-099e2e43c6bf.png)
![movingmean0 7r12](https://cloud.githubusercontent.com/assets/9679702/8330475/80c984de-1a79-11e5-9cfb-73f1258354be.png)
![movingmean0 05r12](https://cloud.githubusercontent.com/assets/9679702/8330476/80cfdf14-1a79-11e5-9606-a3a1271621b7.png)
![movingmean0 1r12](https://cloud.githubusercontent.com/assets/9679702/8330477/80d3915e-1a79-11e5-84e3-2c3b3dfce840.png)

**Comment by geraintpalmer** [comment]
Continuous markov chain simulation in blue, queueing network simulation in green:
![simvsanalsim](https://cloud.githubusercontent.com/assets/9679702/8356542/ec08bcb8-1b4d-11e5-945f-07dc3dc14156.png)
(Couldn't quite get the axis right atm) So probably nothing to do with discretisation

**Comment by drvinceknight** [comment]
That's a shame... :( What are you going to try next?

**Comment by geraintpalmer** [comment]
Run it with 1 node, see if same happens there (1 node system has same simulation, but different markov chain, may be able to deduce where the problem lies)

**Comment by drvinceknight** [comment]
Yeah good idea.

**Comment by geraintpalmer** [comment]
Hang on, might have found bug in simulation....

**Comment by drvinceknight** [comment]
<Holds breath...>

**Comment by paulharper72** [comment]
Btw, missing an epsilon in code, such that time to deadlock minus epsilon (epsilon suitably chosen to get analytical and simulation results to match) unfortunately is not classed as a bug ;)

**Comment by geraintpalmer** [comment]
Results of 1 node network::::::
![plotviolr11](https://cloud.githubusercontent.com/assets/9679702/8569352/9b9f4aa0-256e-11e5-818c-8cd06dd8f90d.png)
![plotvioln1](https://cloud.githubusercontent.com/assets/9679702/8569354/a02bedc6-256e-11e5-83af-0e6d1add8d06.png)
![plotviolmu1](https://cloud.githubusercontent.com/assets/9679702/8569358/a4d61644-256e-11e5-97f7-2ff2c06caa7e.png)
![plotvioll1](https://cloud.githubusercontent.com/assets/9679702/8569360/aa21aef6-256e-11e5-9196-331b52d5691e.png)

**Comment by geraintpalmer** [comment]
Don;t know what's going on with mu1 though....

**Comment by drvinceknight** [comment]
So that's showing a perfect match right?

**Comment by geraintpalmer** [comment]
Yep, perfect. So either:
- markov chain of 2 node is incorrect OR
- the mistakes I found in simulation (that should've only affected 1 node simulation) actually was affecting the 2 node simulation

So I'm running the 2 node simulation with the corrections now, see if that affects anything

**Comment by drvinceknight** [comment]
Ok cool... Let us know if that changes anything...

**Comment by geraintpalmer** [comment]
Simulation running now. VERY EARLy results (only a few data points, rest still running) not looking good:
![earlyresults](https://cloud.githubusercontent.com/assets/9679702/8571449/caee5976-257e-11e5-8103-1ccccb64b102.png)
Probably the MC

**Comment by drvinceknight** [comment]
:(

I think the MC might be forgetting something... Have you gotten anywhere
with trying to fit something to the error?

**Comment by geraintpalmer** [comment]
Not yet, trying to derive the MC again (again) atm. Then I'll look into that.

**Comment by drvinceknight** [comment]
Cool.

**Comment by geraintpalmer** [comment]
1Node network: The effect of varying r11 on the effect of mu1:
![varymu1r11](https://cloud.githubusercontent.com/assets/9679702/8626196/2bc33574-273b-11e5-9fbc-a6ed7ea12606.png)

**Comment by drvinceknight** [comment]
Write down here the interpretation we came to.

**Comment by geraintpalmer** [comment]
So:
- At low service rates (below a threshold, say 2.2) the arrival rate is relatively large, and so we can assume a saturated system. At this point services where the customer leaves do not affect the system, but services where a customer gets blocked leads to deadlock. And so increasing the service rate just increases the chances of getting blocked, and so deadlocked.
- Above this threshold, the service rate is large enough that we cannot assume a saturated system. And that services where customers exit the system does affect the number of people in the system. Thus increasing the service rate removes people from the system, and less chance of getting blocked, and so deadlocked.

**Comment by drvinceknight** [comment]
:+1:

**Comment by geraintpalmer** [comment]
Results from another simulation model (1000 iterations):
![varyl1plot](https://cloud.githubusercontent.com/assets/9679702/8708423/cb75c568-2b33-11e5-9f41-6a7260b0bc6a.png)

**Comment by geraintpalmer** [comment]
Plotting MPE against varying parameters: varying n1, n2, L1, L2 not interesting, however varying r12, r21, mu1 and mu2 produce these:

![mpe_r21](https://cloud.githubusercontent.com/assets/9679702/8724892/ff2584bc-2bc8-11e5-8484-dc1d0c1d6bb3.png)
![mpe_r12](https://cloud.githubusercontent.com/assets/9679702/8724895/021b0408-2bc9-11e5-894a-47364cef684b.png)
![mpe_mu2](https://cloud.githubusercontent.com/assets/9679702/8724896/02279b8c-2bc9-11e5-92b8-f5e4cd1de930.png)
![mpe_mu1](https://cloud.githubusercontent.com/assets/9679702/8724897/022b888c-2bc9-11e5-9afc-391a74b5d42b.png)

So I think the MC is missing something with the transitions from one node to another.

**Comment by geraintpalmer** [comment]
Formulating the MC without using (i, j) formulation for the 2 node network:
![plotvaryl newform](https://cloud.githubusercontent.com/assets/9679702/8775050/5f9ed2ba-2edc-11e5-873a-cfc7d0802beb.png)

**Comment by geraintpalmer** [comment]
And the other parameter changes::
![plotl2nf](https://cloud.githubusercontent.com/assets/9679702/8775920/d403fb32-2ee4-11e5-9086-66868c852388.png)
![plotmu1nf](https://cloud.githubusercontent.com/assets/9679702/8775923/dc6c9144-2ee4-11e5-937a-752ce4460d28.png)
![plotmu2nf](https://cloud.githubusercontent.com/assets/9679702/8775925/e21983fe-2ee4-11e5-8b8b-95156231cd55.png)
![plotn1nf](https://cloud.githubusercontent.com/assets/9679702/8775930/e7ab3510-2ee4-11e5-870d-87c6f8758bc3.png)
![plotn2nf](https://cloud.githubusercontent.com/assets/9679702/8775932/ebe089aa-2ee4-11e5-903d-3413ef2397fa.png)
![plotr12nf](https://cloud.githubusercontent.com/assets/9679702/8775938/f322bdfa-2ee4-11e5-8e30-2531a8511314.png)
![plotr21nf](https://cloud.githubusercontent.com/assets/9679702/8775940/f7d96ace-2ee4-11e5-8090-26fd4cdc9ef0.png)

**Comment by drvinceknight** [comment]
:+1:

**Comment by geraintpalmer** [comment]
This has now all been fixed by e3cf4346b742e9655bcfb5c48cd019d27a53fdec.

The mistake: The two states that lead to deadlock (n1, n2+2) and (n1+2, n1) also had transitions to the state (n1+1, n2+1) as well as to (-1). The wasn't obvious as I thought that this was all tied up in the nice state space but wasn't.

Graphs of final MC:::

![plotl1fixed](https://cloud.githubusercontent.com/assets/9679702/8781100/1cd5256e-2f05-11e5-94f0-162ad9cec3ae.png)
![plotl2fixed](https://cloud.githubusercontent.com/assets/9679702/8781106/21e21a44-2f05-11e5-8018-cc00bddfa8e5.png)
![plotmu1fixed](https://cloud.githubusercontent.com/assets/9679702/8781115/2c29ef54-2f05-11e5-9908-7acb0f9c1e74.png)
![plotmu2fixed](https://cloud.githubusercontent.com/assets/9679702/8781119/3126a696-2f05-11e5-8887-feb1f364725f.png)
![plotn1fixed](https://cloud.githubusercontent.com/assets/9679702/8781124/36bc2d92-2f05-11e5-8fa1-ad5ad0a393e2.png)
![plotn2fixed](https://cloud.githubusercontent.com/assets/9679702/8781129/3accf1aa-2f05-11e5-878f-768c970053bb.png)
![plotr12fixed](https://cloud.githubusercontent.com/assets/9679702/8781136/4468dc92-2f05-11e5-8e25-e0314ebfc368.png)
![plotr21fixed](https://cloud.githubusercontent.com/assets/9679702/8781144/49ad0a98-2f05-11e5-9b64-684b35f92b0f.png)

**Comment by drvinceknight** [comment]
:fireworks:
