### ISSUE TITLE
Look in to drawing

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#4]
You will want tikz code, Sage and networkX might be able to produce the tikz for you (not sure but am curious to find out).

**Comment by geraintpalmer** [comment]
This is very easy:
Make a graph G in sage, then type latex(G).
Spits out tikz code.

**Comment by drvinceknight** [comment]
Cool, you can always tweak the tikz then.
