### ISSUE TITLE
Obtain mean time till absorption

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#7]
Do so analytically (brute force: no need for anything smart).

**Comment by geraintpalmer** [comment]
python code written to find this

**Comment by drvinceknight** [comment]
Nice: how is it looking? Sensible numbers? Can you get simulation to verify now? Get a plot like the one on my blog.

**Comment by geraintpalmer** [comment]
Thats the next step.
Trying to think how I can organise results, loads of variables, lots of results (a time to absorbtion for each state)

**Comment by drvinceknight** [comment]
Don't let it mess with your simulation architecture though.

You could just simulate: spit out data and write something that analyses
the data? (Goes through and counts states etc... Write a nice class that
just updates itself...)

**Comment by geraintpalmer** [comment]
I was going to make a copy of the simulation for this repo, and change that one?

**Comment by drvinceknight** [comment]
It would be nice to avoid that. Why not just get your simulation to spit
out the data and write something that analyses that? A class that goes
through and counts etc...
