### ISSUE TITLE
Verify mean time till absorption.

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/DetectingDeadlockInQingNetworkSimulation#8]
Depends on #7 and being able to identify deadlock in a simulation.

**Comment by geraintpalmer** [comment]
Markov chain model & simulation model now give same results for the mean times to deadlock from each state

**Comment by paulharper72** [comment]
+1

**Comment by drvinceknight** [comment]
That's awesome Geraint, can you throw some plots on this issue for varying
demand? (same plots as for the blog post of mine)

**Comment by geraintpalmer** [comment]
![image](https://cloud.githubusercontent.com/assets/9679702/7368424/9e62bad0-ed9f-11e4-8160-e507588a720e.jpg)
This sort of thing ie? Working on it now

**Comment by drvinceknight** [comment]
Yeah except you can get a smooth plot for the analytical version and get box plots for the simulation (not two scatter plots). Like this:

![](http://vincent-knight.com/unpeudemath/assets/images/expected_wait.png)

**Comment by drvinceknight** [comment]
You should also plot not just for varying Lambda but for varying exit probabilities etc...

**Comment by geraintpalmer** [comment]
For n1 = 3, n2 = 2, mu1 = 10, mu2 = 8, r12  = 0.25, r21 = 0.15, L2 = 5 and varying L1:
![varyingl1](https://cloud.githubusercontent.com/assets/9679702/7369221/18c54632-eda8-11e4-9333-89fb85a73492.png)

**Comment by geraintpalmer** [comment]
Will run simulation now, may take a while to run every scenario

**Comment by drvinceknight** [comment]
Like in my blog post you don't have to run every one for the simulation.

**Comment by drvinceknight** [comment]
Also plot on same plot.

**Comment by geraintpalmer** [comment]
![theoretical_vs_simulation_vary_l1](https://cloud.githubusercontent.com/assets/9679702/7370966/a6b0dddc-edb5-11e4-9e8d-5b485c51f57f.png)
I need to simulate for more iterations though

**Comment by geraintpalmer** [comment]
For n1 = 3, n2 = 2, mu1 = 10, mu2 = 8, r21 = 0.15, L1 = 4, L2 = 5 and varying r12:
![theoretical_vs_simulation_vary_r12](https://cloud.githubusercontent.com/assets/9679702/7373847/c8286dde-edc6-11e4-8381-9c7876c46709.png)

**Comment by drvinceknight** [comment]
Are you plotting these correctly? Should the boxes be nudged over by 1 unit?

**Comment by geraintpalmer** [comment]
No they are plotted fine, maybe I need more iterations? There are a lot of outliers above.

**Comment by drvinceknight** [comment]
> No they are plotted fine, maybe I need more iterations? There are a lot of outliers above.

100% sure? Of by 1 indexing errors... Double check to be sure.

Yeah could be the outliers, possibly more iterations... How many are you doing now?

**Comment by geraintpalmer** [comment]
Sure.
varying the L1 was 150 iterations, varying r12 was 250 iterations.
Isn't the red line median, not mean? So maybe the means do line up, but not medians because of the distribution?

**Comment by drvinceknight** [comment]
Yeah more iterations would be good...

Good point about median/mean... I still think you should be able to get a closer fit than that.

Way more iterations (order of 10^3 or 10^4 if run time is not stupid).

Be sure that you're not just plotting wrong and off by 1...

**Comment by geraintpalmer** [comment]
Showing means:
![theoretical_vs_simulation_vary_r12_showmeans](https://cloud.githubusercontent.com/assets/9679702/7374410/1a3092f2-edca-11e4-9c52-d87bbfe87a89.png)

**Comment by drvinceknight** [comment]
NICE.

Run for longer just because you can, also I think there's a way to get rid
of the outliers in the box plot (might as well do that).

Also throw in a couple for different starting states.
